### ISSUE TITLE
Wiper Command

### ISSUE THREAD

**Issue by mlemm99** [astuff/pacmod_dbc#35]
## Overview
Add 1 more intermittent level to support more platforms.

## Wiper Command
Message Name: WIPER_CMD
Message ID (Decimal): 308
Message ID (Hexadecimal): 0x134
Frame Format: Standard
Data Length Code: 8 (Future: 2)
TX Node: PACMOD
Message Rate: 30 Hz

## Current
|Name|Type|Bitpos|Length|Factor|Offset|Min|Max|Unit|
|---|---|---|---|---|---|---|---|---|
|ENABLE|Unsigned|0|1|1|0|0|1||
|IGNORE_OVERRIDES|Unsigned|1|1|1|0|0|1||
|CLEAR_OVERRIDE|Unsigned|2|1|1|0|0|1||
|WIPER_CMD  **1**|Unsigned|15|8|1|0|0|1||

**1**
7=High, 6=Low, 5=Intermittent 5, 4=Intermittent 4, 3=Intermittent 3, 2=Intermittent 2, 1=Intermittent 1, 0=Wipers Off

## Proposed
|Name|Type|Bitpos|Length|Factor|Offset|Min|Max|Unit|
|---|---|---|---|---|---|---|---|---|
|ENABLE|Unsigned|0|1|1|0|0|1||
|IGNORE_OVERRIDES|Unsigned|1|1|1|0|0|1||
|CLEAR_OVERRIDE|Unsigned|2|1|1|0|0|1||
|WIPER_CMD  **1**|Unsigned|15|8|1|0|0|1||

**1**
8=High, 7=Low, 6=Intermittent 6, 5=Intermittent 5, 4=Intermittent 4, 3=Intermittent 3, 2=Intermittent 2, 1=Intermittent 1, 0=Wipers Off

**Comment by JWhitleyWork** [comment]
So, this is purely because we have a "defined architecture" for system types (for example, the WIPER_CMD is an "IntSystem," I would prefer to have the SPRAYER_CMD be another system (BoolSystem). It avoids coding a special-case for the Wiper system in the firmware and the driver. Currently STEER_CMD is the only special-case system because it needs both the position and rotation rate in order to work properly. Do you have any problems with this?

**Comment by JWhitleyWork** [comment]
Closing in favor of #37.

**Comment by mlemm99** [comment]
add intermittant level

**Comment by asaxsma** [comment]
255 - HIGH, 254 - MEDIUM, 253 - LOW, 11 - INTERMITTENT10 (fastest) through INTERMITTENT1 (slowest), 0 - OFF

**Comment by JWhitleyWork** [comment]
Closed by #42.
